manifest:
  remotes:
    - name: LairdCP
      url-base: https://github.com/LairdCP
    - name: ncs
      url-base: https://github.com/nrfconnect

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: Pinnacle_100_Sample_Applications
      path: pinnacle_100_sample_applications
      remote: LairdCP
    - name: sdk-nrf
      path: nrf
      revision: 843fb6fd97b3672daae67cbe1ede8f310837a3d5
      remote: ncs
      import: true
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: 40017182614910d5c8f42504f6bf3025c72626f3
      remote: LairdCP
      import: true
    - name: zephyr-hal-lairdconnectivity
      path: zephyr/ext/hal/lairdconnectivity
      revision: f2e46c9ad8da72868d48b1eb2daf623c97817b42
      remote: LairdCP
    - name: zephyr_boards
      path: zephyr/boards/arm
      revision: 5c54980b63737e8286ae097d103c7c57c53905e8
      remote: LairdCP
    #- name: zephyr_lib
    #  path: modules/zephyr_lib
    #  remote: LairdCP

  self:
    path: pinnacle_100_sample_applications_manifest
