manifest:
  remotes:
    - name: CanvasDM
      url-base: https://github.com/CanvasDM
    - name: LairdCP
      url-base: https://github.com/LairdCP

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: Pinnacle_100_Sample_Applications
      revision: 13d5c7190ca1c1624706153a1124c8c2bb224c0b
      remote: LairdCP
    - name: sdk-nrf
      path: nrf
      revision: 9a9d1a5c4f5483a7c55b259df69346b702987238
      remote: LairdCP
      import:
        # Please keep this list sorted alphabetically.
        name-blocklist:
          - Alexa-Gadgets-Embedded-Sample-Code
          - canopennode
          - cirrus
          - civetweb
          - connectedhomeip
          - find-my
          - hal_st
          - homekit
          - loramac-node
          - lvgl
          - matter
          - mbed-cloud-client
          - nrf-802154
          - openthread
          - sdk-lc3
    - name: zephyr
      revision: 450dfa9a36f272d56c9bbe3642de3f97ebafc62a
      remote: LairdCP
      import:
        # In addition to the zephyr repository itself, NCS also
        # imports the contents of zephyr/west.yml.
        # Only the projects explicitly named in the
        # following whitelist are imported.
        #
        # Note that the zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - cmsis
          - fatfs
          - hal_nordic
          - libmetal
          - littlefs
          - mbedtls
          - mcumgr
          - mipi-sys-t
          - net-tools
          - nrf_hw_models
          - open-amp
          - openthread
          - segger
          - tinycrypt
          - zcbor
    - name: zephyr_lib
      path: modules/lib/laird_connect/zephyr_lib
      revision: c5db60e1a3fd580671f793144d86089b56dfc600
      remote: LairdCP
    - name: network_monitor_module
      path: modules/lib/laird_connect/network_monitor
      revision: bb7908926648ab07ee69c4308dfd3cf334cc5efe
      remote: CanvasDM

  self:
    path: Pinnacle_100_Sample_Applications_public_manifest
